### ISSUE TITLE
Main.js Module

### ISSUE THREAD

**Issue by curtwebb94** [nss-daytime-cohort-63/Exomine---Team-One#11]
* **I'm submitting a ...**
  - [ ] bug report
  - [X ] feature request

* **What is the current behavior?**
Missing content in the main.js module.

* **What is the expected behavior?**
when the variable is created it will connect main.js to index.html id, "container", then this will display body content.

**Comment by laurafurnivall** [comment]
given the user opens the application
when they view the content
then the user can use the page
